# Generated by Django 5.0.2 on 2026-02-28 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                help_text="User who owns this task",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["-created_at"], name="tasks_created_d28591_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["completed"], name="tasks_complet_563b30_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["owner"], name="tasks_owner_i_11d805_idx"),
        ),
    ]
